### ISSUE TITLE
BAMIndexMetaData incorrect when index results from .crai->.bai conversion

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#531]
The BAMIndex metadata that results from internal conversion of a .crai index to a .bai has incorrect values for "alignedRecords" and "unalignedRecords."  It looks like alignedRecords is set to the size in bytes of the original slice that corresponds to the CRAI entry (for multi-ref slices there can will be a CRAI entry for each reference covered by the slice), rather than the number of records covered by that entry, and unalignedRecords will always be 0. Either way it way overstates the number of records covered by the index entries. It doesn't appear that the CRAI format has any way to store this information so its lost when the .crai is created.

Note that this doesn't happen when htsjdk produces the .bai index directly, which is the current default behavior, since it has access to the original container and slice.

**Comment by droazen** [comment]
@vadimzalunin Can you comment on this?

**Comment by cmnbroad** [comment]
I think the problem is [here](https://github.com/samtools/htsjdk/blob/master/src/java/htsjdk/samtools/cram/CRAIIndex.java#L143) where the field is set during conversion, though the real problem is that during conversion we don't have access to the correct #.

**Comment by vadimzalunin** [comment]
the current CRAI spec doesn't have number of records per slice which is required for BAM metadata. Long story, but this is a known issue and should be addressed in the next CRAI release. 
https://github.com/samtools/hts-specs/issues/146

**Comment by cmnbroad** [comment]
See related discussion on proposed [CRAI updates](https://github.com/samtools/hts-specs/issues/137).

**Comment by tfenne** [comment]
Confirmed still present on current master.

Wrote a 30-record CRAM, then built **only** a CRAI (no BAI) so the reader has to do the CRAI to BAI conversion, and asked for the index metadata:

```
files=[c.cram.crai, c.cram, r.fasta.fai, r.fasta]
aligned=0  unaligned=0     <- expected aligned=30
```

For comparison, the same file indexed natively as a BAI reports `aligned=30 unaligned=0` correctly. So the counts are still lost when the index is derived from a CRAI, just as described -- the value now comes back as 0 rather than a byte count, but it is equally wrong.

As the issue notes, CRAI has nowhere to store these counts, so a converted index cannot reconstruct them. Worth deciding whether `BAMIndexMetaData` should report 'unknown' rather than a plausible-looking 0, since 0 is indistinguishable from a genuinely empty reference and silently misleads callers.

This is also the answer to #1752, which asks for a fast aligned-read count from a CRAM index -- it cannot be satisfied through a CRAI.
